# Generated by Django 5.2.7 on 2025-11-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscriptionpayment_stripe_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
