# Generated by Django 5.2.7 on 2025-12-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_usersubscription_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='invoice_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
