# Generated by Django 5.2.7 on 2025-12-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscriptionpayment_invoice_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_connected_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
